### ISSUE TITLE
Getting Started Instructions Failing

### ISSUE THREAD

**Issue by hammadzz** [SC5/serverless-kms-secrets#13]
Setup as in instructions (serverless-kms-secrets v1.0.2) yet it fails when trying to encrypt a key

Added to my serverless.yml
``` yaml
custom:
  serverless-kms-secrets:
    secretsFile: kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
```

Ran this command
```
serverless encrypt -n SECRETS:MY_SECRET -v [my_secret] -k [my_key_id]
```

**The error I see:**
```
 ENOENT: no such file or directory, lstat '/Users/[MyUser]/Documents/[myproject]/kms-secrets.dev.us-east-1.yml'
```
